
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/black_list
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  file: logs/application.log
  level:
    root: warn